name: Update Writing (Qiita & note)

on:
  schedule:
    # 00:21 UTC = 09:21 JST（毎朝）
    - cron: "21 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: update-writing
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests feedparser python-dateutil

      - name: Update READMEs (Qiita/note)
        env:
          QIITA_USER: "Sh1ragami"
          NOTE_USER: "sh1ragami"
          # 複数READMEに対応（日本語/英語）
          README_PATHS: "README.md,README.jp.md"
          # 単一にしたい場合は README_PATH を使用: "README.md"
          MAX_ITEMS: "5"
          # 並び順: desc / asc（省略時 desc）
          SORT_ORDER: "desc"
          # マーカーをカスタムしたい場合
          # WRITING_SECTION_START: "<!--START:WRITING-->"
          # WRITING_SECTION_END: "<!--END:WRITING-->"
          # 任意: Qiita API トークン（レート緩和用）
          # QIITA_TOKEN: ${{ secrets.QIITA_TOKEN }}
        run: |
          python .github/scripts/update_writing.py

      - name: Commit & push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(readme): auto-update Writing (Qiita/note, ja+en)"
          file_pattern: |
            README.md
            README.en.md
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
